language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rtheory/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rtheory/docker-react npm run test